name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  Bless:

    runs-on: rust:latest

    steps:
    - uses: actions/checkout@v3
    - name: lint
      run: cargo clippy --release -- -D warnings

